### ISSUE TITLE
gh page not working

### ISSUE THREAD

**Issue by ryan-hill** [fawda123/SFS_GIS_R_training#1]
I forked this repo to start working on it and I can't get the gh-page to work correctly - I get a 404 error. I tested it on 2 other repos that I forked from Marc and one is working but I don't know why.

Not working:
https://ryan-hill.github.io/AWRA_GIS_R_Workshop/
https://ryan-hill.github.io/SFS_GIS_R_training/

Working: 
https://ryan-hill.github.io/gis_in_action_r_spatial/

**Comment by fawda123** [comment]
I think we should just build it from scratch.  It's something I've been meaning to learn to do anyway. 

This looks like a good guide: https://rmarkdown.rstudio.com/rmarkdown_websites.html
